on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Run release-please with debug
      run: |
        npx release-please@latest release-pr --token=${{ secrets.GITHUB_TOKEN }} --repo-url=${{ github.repository }} --debug
